[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.8.0"
ic-cdk-macros = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
candid = "0.9.11"

[lib]
crate-type = ["cdylib"]
